services:
  - type: web
    name: laundry-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: ./backend
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: mongodb+srv://Glitch:PETnvMU8X0414oW2@glitch.u5ylwcm.mongodb.net/?retryWrites=true&w=majority&appName=Glitch
      - key: FRONTEND_URL
        value: ludira.vercel.app
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-here
      - key: JWT_EXPIRE
        value: 7d
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        value: laubuoy@gmail.com
      - key: EMAIL_PASS
        value: ofqfcb3m

  - type: web
    name: laundry-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: ./laundry-app
    envVars:
      - key: REACT_APP_API_URL
        value: https://ludiralaundry.onrender.com
